name: Validate test suites
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get venom
        run: |
          wget -q -O venom https://github.com/ovh/venom/releases/download/v1.0.1/venom.linux-amd64
          chmod +x venom
          ./venom update || true
      - name: Execute the test plan
        run: |
          ./venom run --var="target_site=https://righettod.eu" --var="internet_facing=true" --var="logout_url=/logout" tests_suite.yml

